### PR TITLE
Add info to README about TLS 1.2/1.3 support

### PR DESCRIPTION
**Pull request by AaronAtDuo**

### CODE REVIEW

**Comment by yizshi** [comment]
https://raw.githubusercontent.com/actions/python-versions/main/versions-manifest.json
seems python3.6 should pass. Re-run the job

**Review by yizshi — APPROVED** [review]
lgtm, ci failed for unknown reason

**Comment by petiepooo** [comment]
Python 3.6 is EOL.  Recommend dropping 3.6 and adding 3.9 and 3.10.

**Comment by petiepooo** [comment]
Oops, i meant 3.10 and 3.11 to add..  see #44

**Pull request merged**
